name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: humble-ros-base

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
