name: ROS2 CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - iron 
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-ros-base-latest
            ros_distribution: iron
            ros_version: 2            
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
          skip-tests: true